export interface IDatosServicio {
    fecha_cruce: Date,
    guid_archivo: string,
    anio: number,
    mes: number,
    mercado: string,
    margen_operacional: string,
    ventas_totales_regulados: string,
    ventas_totales_areas_especiales: string,
    ventas_barrios_subnormales: string,
    ventas_nuevos_regulados: string,
    ventas_totales_finales: string,
    num_usuarios_regulados: string,
    ventas_totales_regulados_m2: string,
    garantia_pago_contratos: string,
    ponderador_derivx: string,
    energia_cubierta_mecanismo: string,
    precio_energia_comprada: string,
    precio_promedio_ponderado: string,
    costo_financiero_garantias: string,
}